In [1]:
import numpy as np
import pandas as pd
import val

In [2]:
# Identity Matrix
# arr = np.eye(3,3) 
arr = np.eye(3,3, k=-1)
print(arr)

[[0. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]]


In [3]:
arr[arr == 1] = 7
arr[arr == 0] = 2
print(arr)

[[2. 2. 2.]
 [7. 2. 2.]
 [2. 7. 2.]]


In [4]:
arr[1,:]

array([7., 2., 2.])

In [5]:
arr[:,-1]

array([2., 2., 2.])

In [6]:
sorted_arr = np.sort(arr) # sorted by row
print(sorted_arr)

[[2. 2. 2.]
 [2. 2. 7.]
 [2. 2. 7.]]


In [7]:
sorted_col_arr = np.sort(arr, axis=0, kind = "heapsort") # Sorted by column
print(sorted_col_arr)

[2. 2. 7.]


In [8]:
# Copy of array
arr_view = sorted_arr.view() # Any change does affect main
arr_copy = sorted_arr.copy() # Any change does not affect main


# List Comprehension
* [expression_action if condition else option for I in list ]

In [9]:
my_string = "HelloIamManish"
my_string = "".join( [ i if i.islower() else " " + i for i in my_string])[1:]
print(my_string)

Hello Iam Manish


In [10]:
bits = [False, True, False, True, True]
new_bit = [1 if b==True else 0 for b in bits ]  
print(bits, "\n")
print(new_bit)

[False, True, False, True, True, False] 

[0, 1, 0, 1, 1, 0]


# Dictionary Comprehension
* Create dictionary from  1. list, 2. tuple, 3. dataframes
* Modify dictionary in place
* Create complex data structures: 1. dict of lists, 2. list of dict

In [11]:
names = ['manish', 'ajay', 'jacob']
profs = ['programmer', 'actor', 'painter']
my_dict = {
    names[i]:profs[i] for i in range(len(profs))
}
print(my_dict)

{'manish': 'programmer', 'ajay': 'actor', 'jacob': 'painter', 'Ravi': 'singer'}


In [12]:
names = ('manish', 'ajay', 'jacob')
profs = ('programmer', 'actor', 'painter')
my_tuple_dict = {
    names[i]:profs[i] for i in range(len(profs))
}
print(my_tuple_dict)

{'manish': 'programmer', 'ajay': 'actor', 'jacob': 'painter'}


In [13]:
names = pd.DataFrame(['manish', 'ajay', 'jacob'])
profs = pd.DataFrame(['programmer', 'actor', 'painter'])
my_df_dict = {
    names[0][i]:profs[0][i] for i in range(len(profs))
}
print(my_df_dict)

{'manish': 'programmer', 'ajay': 'actor', 'jacob': 'painter', 'Navjeet': 'Dancer'}


In [14]:
# Modify the list
# Accessing keys and value both
my_new_dict = {key+"-Male":val for (key, val) in my_dict.items()}
print(my_new_dict)

{'manish-Male': 'programmer', 'ajay-Male': 'actor', 'jacob-Male': 'painter', 'Ravi-Male': 'singer'}


In [15]:
# Without item function we would be accessing only keys 
my_new_dict = {key+"-Male": None for key in my_dict}
print(my_new_dict)

{'manish-Male': None, 'ajay-Male': None, 'jacob-Male': None, 'Ravi-Male': None}


In [16]:
# Change in the keys
my_new_dict = {(key+"-Male" if key!= "ajay" else "anita-Female"):val for (key, val) in my_dict.items()}
print(my_new_dict)

{'manish-Male': 'programmer', 'anita-Female': 'actor', 'jacob-Male': 'painter', 'Ravi-Male': 'singer'}


In [17]:
# Change in the keys and values
my_new_dict = {(key+"-Male" if key!= "ajay" else "anita-Female"): (val if val != "actor" else "actress") for (key, val) in my_dict.items()}
print(my_new_dict)

{'manish-Male': 'programmer', 'anita-Female': 'actress', 'jacob-Male': 'painter', 'Ravi-Male': 'singer'}


# Creating Dictionary of list

In [18]:
import random
bases = ["A", "T", "G", "C"]
strand1 = random.choices(bases, k=10)
# strand2 = random.choices(bases, k=10)
print(strand1)

['G', 'G', 'T', 'A', 'T', 'G', 'C', 'G']


In [19]:
dna = {key:[] for (key, val) in enumerate(strand1)}
print(dna)

{0: [], 1: [], 2: [], 3: [], 4: [], 5: [], 6: [], 7: []}


In [20]:
for key in strand1:
    print(f"key:{key}")

key:G
key:G
key:T
key:A
key:T
key:G
key:C
key:G


In [21]:
for key in enumerate(strand1):
    print(f"key:{key}")

key:(0, 'G')
key:(1, 'G')
key:(2, 'T')
key:(3, 'A')
key:(4, 'T')
key:(5, 'G')
key:(6, 'C')
key:(7, 'G')


In [22]:
for key, val in enumerate(strand1):
    print(f"key:{key}: val:{val}")

key:0: val:G
key:1: val:G
key:2: val:T
key:3: val:A
key:4: val:T
key:5: val:G
key:6: val:C
key:7: val:G


In [23]:
# Putting values for base
dna = {key:[val, None] for (key, val) in enumerate(strand1)}
print(dna)

{0: ['G', None], 1: ['G', None], 2: ['T', None], 3: ['A', None], 4: ['T', None], 5: ['G', None], 6: ['C', None], 7: ['G', None]}


In [24]:
dna = {key:[val, ("T" if val == "A" else "A" if val == "T" 
                  else "C" if val == "G" else "G")] for (key, val) in enumerate(strand1)}

for (key,value) in dna.items():
    print(key, ':', value)

0 : ['G', 'C']
1 : ['G', 'C']
2 : ['T', 'A']
3 : ['A', 'T']
4 : ['T', 'A']
5 : ['G', 'C']
6 : ['C', 'G']
7 : ['G', 'C']


# Creating List of directory

In [25]:
keys = ["id", "username", "password"]
users = ["manish", "shakeel", "navjeet"]

list_dict = [{} for i in range(len(users))]
print(list_dict)

[{}, {}, {}, {}]


In [26]:
# Putting values to Dictionary
# Putting the key values from the keys list
list_dict = [{key : None for key in keys } for i in range(len(users))]
print(list_dict)

[{'id': None, 'username': None, 'password': None}, {'id': None, 'username': None, 'password': None}, {'id': None, 'username': None, 'password': None}, {'id': None, 'username': None, 'password': None}]


In [27]:
# Putting values to Dictionary
# Putting the values from the users list

list_dict = [{key:(i if key == "id" else users[i] if key == "username" else None) for key in keys} for i in range(len(users))]
print(list_dict) 

[{'id': 0, 'username': 'manish', 'password': None}, {'id': 1, 'username': 'shakeel', 'password': None}, {'id': 2, 'username': 'navjeet', 'password': None}, {'id': 3, 'username': 'Kartik', 'password': None}]


<h3>Creating random password using list comprehension, "string.printable"

In [28]:
import random
import string

password = "".join(random.choices(string.printable, k=8))
print(password)

qwF03`y;


In [29]:
# Putting values to Dictionary
# Putting the values from the users list

list_dict = [{key:(i if key == "id" else users[i] if key == "username" else "".join(random.choices(string.printable, k=8))) 
              for key in keys} for i in range(len(users))]
print(list_dict) 

[{'id': 0, 'username': 'manish', 'password': 'Qk:{5Vy['}, {'id': 1, 'username': 'shakeel', 'password': 'y~an{;8H'}, {'id': 2, 'username': 'navjeet', 'password': 'Y-]Jn6km'}, {'id': 3, 'username': 'Kartik', 'password': 'L\rlPuRyf'}]
