In [1]:
!pip install numpy


zsh:1: command not found: pip


In [2]:
import numpy as np

# 1. Create

In [4]:
data = np.random.rand(2,3,4)

zeroes = np.zeros((2,2,2))
full = np.full((2,2,2), 7)
ones = np.ones((2,2,2))

In [5]:
data

array([[[0.63197946, 0.93687163, 0.39911133, 0.17930035],
        [0.70982171, 0.5967851 , 0.66516079, 0.45655156],
        [0.08286169, 0.43339994, 0.51811461, 0.81593309]],

       [[0.45585234, 0.71912147, 0.2594868 , 0.04670697],
        [0.15746765, 0.1578807 , 0.92589407, 0.27785804],
        [0.36813579, 0.28484414, 0.46719121, 0.5043405 ]]])

In [6]:
full

array([[[7, 7],
        [7, 7]],

       [[7, 7],
        [7, 7]]])

In [7]:
ones

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [8]:
arr = np.array([[1,2,3,4],[1,2,3,4]])

In [9]:
type(arr)

numpy.ndarray

In [10]:
arr

array([[1, 2, 3, 4],
       [1, 2, 3, 4]])

# 2. Read

In [11]:
# Attributes
shape = data.shape
size = data.size
types = data.dtype

In [14]:
types

dtype('float64')

In [15]:
# Slicing
arr = data[0]
slicer = data[0][0:2]
reverse = data[-1]
singleval = data[0][0][0]

In [19]:
reverse

array([[0.45585234, 0.71912147, 0.2594868 , 0.04670697],
       [0.15746765, 0.1578807 , 0.92589407, 0.27785804],
       [0.36813579, 0.28484414, 0.46719121, 0.5043405 ]])

In [16]:
arr

array([[0.63197946, 0.93687163, 0.39911133, 0.17930035],
       [0.70982171, 0.5967851 , 0.66516079, 0.45655156],
       [0.08286169, 0.43339994, 0.51811461, 0.81593309]])

In [17]:
slicer

array([[0.63197946, 0.93687163, 0.39911133, 0.17930035],
       [0.70982171, 0.5967851 , 0.66516079, 0.45655156]])

In [13]:
data

array([[[0.8496555 , 0.97240805, 0.56992782, 0.84483832],
        [0.48206751, 0.56386194, 0.38328511, 0.94474075],
        [0.62264942, 0.55445021, 0.24909576, 0.22786525]],

       [[0.59022627, 0.77402142, 0.91253204, 0.90604937],
        [0.17350121, 0.31576644, 0.36229959, 0.11070229],
        [0.20097927, 0.14289693, 0.81421516, 0.23983404]]])

In [20]:
singleval

0.6319794595373655

# 3. Update

In [34]:
list1 = np.random.rand(10) 
list2 = np.random.rand(10) 

In [35]:
list2

array([0.51981135, 0.30303372, 0.82968976, 0.3214754 , 0.12390154,
       0.51528526, 0.48322378, 0.59991698, 0.17418005, 0.99439513])

In [36]:
# Basic Math
add = np.add(list1, list2)
sub = np.subtract(list1, list2)
div = np.divide(list1, list2)
mult = np.multiply(list1, list2)
dot = np.dot(list1, list2)

In [37]:
dot

2.2780466004764732

In [46]:
# Stat Functions
sqrt = np.sqrt(25)
ab = np.abs(-2)
power = np.power(2,7)
log = np.log(10)
exp = np.exp([2,3])
mins = np.min(list1)
maxs = np.max(list1)

In [48]:
print(mins,maxs)

0.14842455209029426 0.839793220894265


In [49]:
data

array([[[0.63197946, 0.93687163, 0.39911133, 0.17930035],
        [0.70982171, 0.5967851 , 0.66516079, 0.45655156],
        [0.08286169, 0.43339994, 0.51811461, 0.81593309]],

       [[0.45585234, 0.71912147, 0.2594868 , 0.04670697],
        [0.15746765, 0.1578807 , 0.92589407, 0.27785804],
        [0.36813579, 0.28484414, 0.46719121, 0.5043405 ]]])

In [50]:
data[0][0][0] = 700

In [51]:
data

array([[[7.00000000e+02, 9.36871631e-01, 3.99111333e-01, 1.79300349e-01],
        [7.09821706e-01, 5.96785100e-01, 6.65160790e-01, 4.56551562e-01],
        [8.28616876e-02, 4.33399939e-01, 5.18114607e-01, 8.15933090e-01]],

       [[4.55852342e-01, 7.19121466e-01, 2.59486803e-01, 4.67069654e-02],
        [1.57467652e-01, 1.57880701e-01, 9.25894066e-01, 2.77858035e-01],
        [3.68135794e-01, 2.84844136e-01, 4.67191209e-01, 5.04340500e-01]]])

In [52]:
data.sort()
data

array([[[1.79300349e-01, 3.99111333e-01, 9.36871631e-01, 7.00000000e+02],
        [4.56551562e-01, 5.96785100e-01, 6.65160790e-01, 7.09821706e-01],
        [8.28616876e-02, 4.33399939e-01, 5.18114607e-01, 8.15933090e-01]],

       [[4.67069654e-02, 2.59486803e-01, 4.55852342e-01, 7.19121466e-01],
        [1.57467652e-01, 1.57880701e-01, 2.77858035e-01, 9.25894066e-01],
        [2.84844136e-01, 3.68135794e-01, 4.67191209e-01, 5.04340500e-01]]])

In [53]:
print(data.shape)

(2, 3, 4)


In [54]:
data = data.reshape((2,2,-1))
data.shape

(2, 2, 6)

In [55]:
zeroes = np.zeros((8))
print(zeroes)
zeroes = np.append(zeroes, [3,4])
print(zeroes)

[0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 3. 4.]


In [27]:
zeroes = np.insert(zeroes, 2, 1)
print(zeroes)

[0. 0. 1. 0. 0. 0. 0. 0. 0. 3. 4.]


# 4. Delete

In [56]:
data

array([[[1.79300349e-01, 3.99111333e-01, 9.36871631e-01, 7.00000000e+02,
         4.56551562e-01, 5.96785100e-01],
        [6.65160790e-01, 7.09821706e-01, 8.28616876e-02, 4.33399939e-01,
         5.18114607e-01, 8.15933090e-01]],

       [[4.67069654e-02, 2.59486803e-01, 4.55852342e-01, 7.19121466e-01,
         1.57467652e-01, 1.57880701e-01],
        [2.77858035e-01, 9.25894066e-01, 2.84844136e-01, 3.68135794e-01,
         4.67191209e-01, 5.04340500e-01]]])

In [57]:
np.delete(data, 0, axis=1)

array([[[0.66516079, 0.70982171, 0.08286169, 0.43339994, 0.51811461,
         0.81593309]],

       [[0.27785804, 0.92589407, 0.28484414, 0.36813579, 0.46719121,
         0.5043405 ]]])

In [58]:
np.save("new array", data)

In [59]:
test = np.load("new array.npy")

In [60]:
test

array([[[1.79300349e-01, 3.99111333e-01, 9.36871631e-01, 7.00000000e+02,
         4.56551562e-01, 5.96785100e-01],
        [6.65160790e-01, 7.09821706e-01, 8.28616876e-02, 4.33399939e-01,
         5.18114607e-01, 8.15933090e-01]],

       [[4.67069654e-02, 2.59486803e-01, 4.55852342e-01, 7.19121466e-01,
         1.57467652e-01, 1.57880701e-01],
        [2.77858035e-01, 9.25894066e-01, 2.84844136e-01, 3.68135794e-01,
         4.67191209e-01, 5.04340500e-01]]])